### ISSUE TITLE
What does install-panda-desk do?

### ISSUE THREAD

**Issue by stevencolinmartin** [qcr/tools#4]
@suddrey-qut what does this too do? Is there any description? Is there any help? 

@btalb how should this be documented?

**Comment by stevencolinmartin** [comment]
Same applies for cluster tools.

**Comment by btalb** [comment]
My preference is:

1.  **Limit `qcr` to convenience tools that improve the workflow on our systems / within QCR**

    Things like listing info about a robot's current state, finding what ROS things are actually currently running, printing status of all GPU cluster machines, creating a code template, etc. 

    Crucially, they must have **no side effects!** Users need to be able to run these without a second-thought or else they won't return once a side effect like installing software or modifying system state burns them.

2. **Store static machine-specific configurations with our [system config tracking tools](https://github.com/qcr/robot_system_configs)**

    We need to split these into robot-specific repos ASAP, but no time has been assigned yet to actually exploring the issue:
https://github.com/qcr/robot_system_configs/issues/5

3. **Figure out how we handle tracking commands that modify system state**

    Adding a basic install script to each robot-specific system config repo has been proposed, but again not explored. Time needs to be allocated to deciding and executing a solution here. 

I think we really need to prioritise making some decisions around how we split all of this up. Things like all of the above have been discussed in isolation but not finalised yet, let alone documented so that contributors like @suddrey-qut have a clear picture.

**Comment by btalb** [comment]
Removed.
